-- ============================================================================
-- migration_colors_families.sql
-- COLOR Step 3 (data) — populate colors.families[] from the reviewed
-- docs/normalization/colors.csv, and sync the reference to the live set.
--
-- STATUS: REVIEW DRAFT 2026-07-08 — DO NOT APPLY until owner approves.
-- Generated from colors.csv (399 codes) — do not hand-edit; regenerate
-- via scratchpad/gen_families_migration.py after editing the CSV.
--
-- Upserts every reviewed code with its families (adds codes the owner created
-- via direct DB edits: Gold/Olive/Olive Grey/Orange Grey Brown/Red Cream),
-- then deletes codes no longer present anywhere (dead junk: Cotton, Kurta
-- Pajama, Melody, Gwalior Boss/Combo, Orion Fab, Light Color, Oricletic).
--
-- hex left null (family-level swatches handled separately). No FK here
-- (migration_colors_fk.sql, applied with the color combobox).
-- ============================================================================

begin;

create temp table colors_seed (code text primary key, families text[] not null) on commit drop;
insert into colors_seed (code, families) values
  ('Black', '{"Black"}'),
  ('Blue', '{"Blue"}'),
  ('Red', '{"Red"}'),
  ('Yellow', '{"Yellow"}'),
  ('Green', '{"Green"}'),
  ('Grey', '{"Grey"}'),
  ('White', '{"White/Cream"}'),
  ('Maroon', '{"Maroon/Wine"}'),
  ('Pink', '{"Pink"}'),
  ('Navy Blue', '{"Blue"}'),
  ('Orange', '{"Orange"}'),
  ('Peach', '{"Peach"}'),
  ('Wine', '{"Maroon/Wine"}'),
  ('Sky Blue', '{"Blue"}'),
  ('Brown', '{"Brown/Beige"}'),
  ('Mustard', '{"Yellow"}'),
  ('Firozi', '{"Blue"}'),
  ('Golden', '{"Gold/Metallic"}'),
  ('Magenta', '{"Pink"}'),
  ('Off White', '{"White/Cream"}'),
  ('Fawn', '{"Brown/Beige"}'),
  ('Gazari', '{"Pink"}'),
  ('Purple', '{"Purple"}'),
  ('Lavender', '{"Purple"}'),
  ('Sea Green', '{"Green"}'),
  ('Pista Green', '{"Green"}'),
  ('Cream', '{"White/Cream"}'),
  ('Peacock Green', '{"Green","Blue"}'),
  ('Lemon', '{"Yellow"}'),
  ('Rust', '{"Orange"}'),
  ('Pista', '{"Green"}'),
  ('Multi Color', '{"Multi/Printed"}'),
  ('Mehndi', '{"Green"}'),
  ('Royal Blue', '{"Blue"}'),
  ('Rama Green', '{"Green"}'),
  ('Mehndi Green', '{"Green"}'),
  ('Printed', '{"Multi/Printed"}'),
  ('Beige', '{"Brown/Beige"}'),
  ('Light Grey', '{"Grey"}'),
  ('Parrot Green', '{"Green"}'),
  ('Teal Grey', '{"Grey","Blue"}'),
  ('Light Brown', '{"Brown/Beige"}'),
  ('Coffee', '{"Brown/Beige"}'),
  ('Light Green', '{"Green"}'),
  ('Light Purple', '{"Purple"}'),
  ('Dark Grey', '{"Grey"}'),
  ('Mustard Yellow', '{"Yellow"}'),
  ('Lemon Yellow', '{"Yellow"}'),
  ('Bottle Green', '{"Green"}'),
  ('Light Blue', '{"Blue"}'),
  ('Teal Blue', '{"Blue"}'),
  ('Skin', '{"Peach"}'),
  ('Olive Green', '{"Green"}'),
  ('Dark Blue', '{"Blue"}'),
  ('Light Peach', '{"Peach"}'),
  ('Red Black', '{"Red","Black"}'),
  ('Dark Green', '{"Green"}'),
  ('Lime Green', '{"Green"}'),
  ('Dark Pink', '{"Pink"}'),
  ('Golden Red', '{"Gold/Metallic","Red"}'),
  ('White Black', '{"White/Cream","Black"}'),
  ('White Blue', '{"White/Cream","Blue"}'),
  ('Peacock Blue', '{"Blue","Green"}'),
  ('Sage Green', '{"Green"}'),
  ('Deep Peach', '{"Peach"}'),
  ('Tussar', '{"Brown/Beige"}'),
  ('White Grey', '{"White/Cream","Grey"}'),
  ('Blueish Grey', '{"Grey"}'),
  ('Khaki', '{"Brown/Beige"}'),
  ('Light Sky Blue', '{"Blue"}'),
  ('Mauve', '{"Purple"}'),
  ('Pink Green', '{"Pink","Green"}'),
  ('White Brown', '{"White/Cream","Brown/Beige"}'),
  ('Black Mustard', '{"Black","Yellow"}'),
  ('Dark Purple', '{"Purple"}'),
  ('Dusty', '{"Yellow"}'),
  ('Golden Maroon', '{"Gold/Metallic","Maroon/Wine"}'),
  ('Hot Pink', '{"Pink"}'),
  ('Light Pink', '{"Pink"}'),
  ('Mehendi Green', '{"Green"}'),
  ('Rama Green (Morni)', '{"Green"}'),
  ('Black Grey', '{"Black","Grey"}'),
  ('Black Red', '{"Black","Red"}'),
  ('Blue Grey', '{"Blue","Grey"}'),
  ('Green Blue', '{"Green","Blue"}'),
  ('Light Pista', '{"Green"}'),
  ('Mouse Grey', '{"Grey"}'),
  ('Peacock Green Off White', '{"Green","White/Cream","Blue"}'),
  ('Red Blue', '{"Red","Blue"}'),
  ('White Red', '{"White/Cream","Red"}'),
  ('Baby Pink', '{"Pink"}'),
  ('Black Line', '{"Black"}'),
  ('Black Neck', '{"Black"}'),
  ('Blue Mustard', '{"Blue","Yellow"}'),
  ('Blue Red', '{"Blue","Red"}'),
  ('Brown Black', '{"Brown/Beige","Black"}'),
  ('Charcoal Grey', '{"Grey"}'),
  ('Design Blue', '{"Blue"}'),
  ('Golden Beige', '{"Gold/Metallic","Brown/Beige"}'),
  ('Grey Red', '{"Grey","Red"}'),
  ('Light Golden', '{"Gold/Metallic"}'),
  ('Light Mehndi', '{"Green"}'),
  ('Light Yellow', '{"Yellow"}'),
  ('Mint Green', '{"Green"}'),
  ('Multi Color White', '{"Multi/Printed","White/Cream"}'),
  ('Navy Blue Orange', '{"Blue","Orange"}'),
  ('Peacock', '{"Green","Blue"}'),
  ('Red Fawn', '{"Red","Brown/Beige"}'),
  ('Red Orange', '{"Red","Orange"}'),
  ('Black Maroon', '{"Black","Maroon/Wine"}'),
  ('Black Rust', '{"Black","Orange"}'),
  ('Brown White', '{"Brown/Beige","White/Cream"}'),
  ('Cream Grey', '{"White/Cream","Grey"}'),
  ('Dark Navy Blue', '{"Blue"}'),
  ('Fawn Blue', '{"Brown/Beige","Blue"}'),
  ('Firozi Green', '{"Blue","Green"}'),
  ('Firozi Grey', '{"Blue","Grey"}'),
  ('Golden Blue', '{"Gold/Metallic","Blue"}'),
  ('Golden Magenta', '{"Gold/Metallic","Pink"}'),
  ('Golden Orange', '{"Gold/Metallic","Orange"}'),
  ('Grey Off White', '{"Grey","White/Cream"}'),
  ('Grey Orange', '{"Grey","Orange"}'),
  ('Grey Pink', '{"Grey","Pink"}'),
  ('Lemon Pink', '{"Yellow","Pink"}'),
  ('Line Black', '{"Black"}'),
  ('Line Blue', '{"Blue"}'),
  ('Mustard Green', '{"Yellow","Green"}'),
  ('Navy Blue Check', '{"Blue","Multi/Printed"}'),
  ('Navy Blue Golden', '{"Blue","Gold/Metallic"}'),
  ('Navy Blue Yellow', '{"Blue","Yellow"}'),
  ('Normal Blue', '{"Blue"}'),
  ('Off White Red', '{"White/Cream","Red"}'),
  ('Orange Red', '{"Orange","Red"}'),
  ('Pistagreen Off White', '{"Green","White/Cream"}'),
  ('Red Golden', '{"Red","Gold/Metallic"}'),
  ('Red Green', '{"Red","Green"}'),
  ('Red Yellow', '{"Red","Yellow"}'),
  ('Yellow Pink', '{"Yellow","Pink"}'),
  ('Black Blue', '{"Black","Blue"}'),
  ('Black Brown', '{"Black","Brown/Beige"}'),
  ('Black Orange', '{"Black","Orange"}'),
  ('Black Print', '{"Black","Multi/Printed"}'),
  ('Black White', '{"Black","White/Cream"}'),
  ('Blue Black', '{"Blue","Black"}'),
  ('Blue Check', '{"Blue","Multi/Printed"}'),
  ('Blue Dot', '{"Blue"}'),
  ('Blue Green', '{"Blue","Green"}'),
  ('Blue Magenta', '{"Blue","Pink"}'),
  ('Blue Off White', '{"Blue","White/Cream"}'),
  ('Blue Pink', '{"Blue","Pink"}'),
  ('Brown Onion', '{"Brown/Beige"}'),
  ('Charcoal', '{"Grey"}'),
  ('Dark Brown', '{"Brown/Beige"}'),
  ('Dark Peach', '{"Peach"}'),
  ('Dusty Orange', '{"Orange"}'),
  ('Dusty Rose', '{"Pink"}'),
  ('Fawn Black', '{"Brown/Beige","Black"}'),
  ('Firozi Black', '{"Blue","Black"}'),
  ('Firozi Golden', '{"Blue","Gold/Metallic"}'),
  ('Forest Green', '{"Green"}'),
  ('Gazari Golden', '{"Pink","Gold/Metallic"}'),
  ('Golden Brown', '{"Gold/Metallic","Brown/Beige"}'),
  ('Golden Yellow', '{"Gold/Metallic","Yellow"}'),
  ('Green Golden', '{"Green","Gold/Metallic"}'),
  ('Green Orange', '{"Green","Orange"}'),
  ('Grey Blue', '{"Grey","Blue"}'),
  ('Light Coffee', '{"Brown/Beige"}'),
  ('Light Maroon', '{"Maroon/Wine"}'),
  ('Light Orange', '{"Orange"}'),
  ('Maroon Check', '{"Maroon/Wine","Multi/Printed"}'),
  ('Morni', '{"Green"}'),
  ('Mustard Red', '{"Yellow","Red"}'),
  ('Navy Blue Fawn', '{"Blue","Brown/Beige"}'),
  ('Navy Blue Green', '{"Blue","Green"}'),
  ('Navy Blue Off White', '{"Blue","White/Cream"}'),
  ('Navy Blue Print', '{"Blue","Multi/Printed"}'),
  ('Navy Red', '{"Blue","Red"}'),
  ('Navy Sky Blue', '{"Blue"}'),
  ('Off White Navy Blue', '{"White/Cream","Blue"}'),
  ('Off White Orange', '{"White/Cream","Orange"}'),
  ('Orange Blue', '{"Orange","Blue"}'),
  ('Orange Golden', '{"Orange","Gold/Metallic"}'),
  ('Orange Magenta', '{"Orange","Pink"}'),
  ('Orange Pink', '{"Orange","Pink"}'),
  ('Peach Magenta', '{"Peach","Pink"}'),
  ('Peach Orange', '{"Peach","Orange"}'),
  ('Pencil Grey', '{"Grey"}'),
  ('Pink Black', '{"Pink","Black"}'),
  ('Pink Blue', '{"Pink","Blue"}'),
  ('Purple Green', '{"Purple","Green"}'),
  ('Red Navy Blue', '{"Red","Blue"}'),
  ('Red Off White', '{"Red","White/Cream"}'),
  ('Sky Blue White', '{"Blue","White/Cream"}'),
  ('Steel Blue', '{"Grey","Blue"}'),
  ('Steel Grey', '{"Grey"}'),
  ('White Green', '{"White/Cream","Green"}'),
  ('White Neck', '{"White/Cream"}'),
  ('White Plain', '{"White/Cream"}'),
  ('White Self', '{"White/Cream"}'),
  ('Yellow Magenta', '{"Yellow","Pink"}'),
  ('Yellow Red', '{"Yellow","Red"}'),
  ('Aqua Blue', '{"Blue"}'),
  ('Black Check', '{"Black","Multi/Printed"}'),
  ('Black Fawn', '{"Black","Brown/Beige"}'),
  ('Black Firozi', '{"Black","Blue"}'),
  ('Black Golden', '{"Black","Gold/Metallic"}'),
  ('Black Green Brown', '{"Black","Green","Brown/Beige"}'),
  ('Black Lavender', '{"Black","Purple"}'),
  ('Black Light Grey', '{"Black","Grey"}'),
  ('Black Magenta', '{"Black","Pink"}'),
  ('Black Off White', '{"Black","White/Cream"}'),
  ('Black Wine', '{"Black","Maroon/Wine"}'),
  ('Black Yellow', '{"Black","Yellow"}'),
  ('Black Zigzag', '{"Black","Multi/Printed"}'),
  ('Blue Brown', '{"Blue","Brown/Beige"}'),
  ('Blue Maroon', '{"Blue","Maroon/Wine"}'),
  ('Blue Orange', '{"Blue","Orange"}'),
  ('Blue Pista', '{"Blue","Green"}'),
  ('Blue Purple Golden', '{"Blue","Purple","Gold/Metallic"}'),
  ('Blue White', '{"Blue","White/Cream"}'),
  ('Blue-Yellow-Pink', '{"Blue","Pink","Yellow"}'),
  ('Bottle Green Golden', '{"Green","Gold/Metallic"}'),
  ('Bright Orange', '{"Orange"}'),
  ('Bright Pink', '{"Pink"}'),
  ('Bright Red', '{"Red"}'),
  ('Brown And Mustard', '{"Brown/Beige","Yellow"}'),
  ('Brown Golden', '{"Brown/Beige","Gold/Metallic"}'),
  ('Brown Green', '{"Brown/Beige","Green"}'),
  ('Brown Khadi', '{"Brown/Beige"}'),
  ('Brown Print', '{"Brown/Beige","Multi/Printed"}'),
  ('Charcoal Black', '{"Grey","Black"}'),
  ('Cherry', '{"Red"}'),
  ('Coffee Brown', '{"Brown/Beige"}'),
  ('Coral', '{"Peach"}'),
  ('Cream With Sky Blue', '{"White/Cream","Blue"}'),
  ('Dark Maroon', '{"Maroon/Wine"}'),
  ('Dark Sky Blue', '{"Blue"}'),
  ('Deep Red', '{"Red"}'),
  ('Dusty Magenta', '{"Pink"}'),
  ('Dusty Mustard Orange', '{"Orange","Yellow"}'),
  ('Dusty Pink', '{"Pink"}'),
  ('Elegant Blue', '{"Blue"}'),
  ('Falsa', '{"Maroon/Wine"}'),
  ('Fawn Brown', '{"Brown/Beige"}'),
  ('Fawn Golden', '{"Brown/Beige","Gold/Metallic"}'),
  ('Fawn Maroon', '{"Brown/Beige","Maroon/Wine"}'),
  ('Fawn Navy Blue', '{"Brown/Beige","Blue"}'),
  ('Fawn Pink', '{"Brown/Beige","Pink"}'),
  ('Fawn With Black', '{"Brown/Beige","Black"}'),
  ('Firozi Off White', '{"Blue","White/Cream"}'),
  ('Flower', '{"Multi/Printed"}'),
  ('Gazari Blue', '{"Pink","Blue"}'),
  ('Gazari Brown', '{"Pink","Brown/Beige"}'),
  ('Gazari Cream', '{"Pink","White/Cream"}'),
  ('Gazari Fawn', '{"Pink","Brown/Beige"}'),
  ('Gazari Green', '{"Pink","Green"}'),
  ('Gazari Navy Blue', '{"Pink","Blue"}'),
  ('Gazari Pink', '{"Pink"}'),
  ('Gazari Yellow', '{"Pink","Yellow"}'),
  ('Gazri Blue', '{"Pink","Blue"}'),
  ('Gold', '{"Gold/Metallic"}'),
  ('Golden Dust Pink', '{"Pink","Gold/Metallic"}'),
  ('Golden Fawn', '{"Gold/Metallic","Brown/Beige"}'),
  ('Golden Firozi', '{"Gold/Metallic","Blue"}'),
  ('Golden Gazari', '{"Gold/Metallic","Pink"}'),
  ('Golden Green', '{"Gold/Metallic","Green"}'),
  ('Golden Light Green', '{"Gold/Metallic","Green"}'),
  ('Golden Mustard', '{"Gold/Metallic","Yellow"}'),
  ('Golden Navy Blue', '{"Gold/Metallic","Blue"}'),
  ('Golden Off White', '{"Gold/Metallic","White/Cream"}'),
  ('Golden Peach', '{"Gold/Metallic","Peach"}'),
  ('Golden Pink', '{"Gold/Metallic","Pink"}'),
  ('Golden Rama Green', '{"Gold/Metallic","Green"}'),
  ('Golden Wine', '{"Gold/Metallic","Maroon/Wine"}'),
  ('Green & Black', '{"Green","Black"}'),
  ('Green Magenta', '{"Green","Pink"}'),
  ('Green Navy Blue', '{"Green","Blue"}'),
  ('Grey Black', '{"Grey","Black"}'),
  ('Grey Brown', '{"Grey","Brown/Beige"}'),
  ('Grey Check', '{"Grey","Multi/Printed"}'),
  ('Grey Green', '{"Grey","Green"}'),
  ('Grey Light', '{"Grey"}'),
  ('Grey Magenta', '{"Grey","Pink"}'),
  ('Grey Maroon', '{"Grey","Maroon/Wine"}'),
  ('Grey With Golden Beads', '{"Grey","Gold/Metallic"}'),
  ('Light Mehndi Green', '{"Green"}'),
  ('Light Sea Green', '{"Green"}'),
  ('Magenta Mustard', '{"Pink","Yellow"}'),
  ('Magenta Off White', '{"Pink","White/Cream"}'),
  ('Magenta Orange', '{"Pink","Orange"}'),
  ('Magenta Pink', '{"Pink"}'),
  ('Magenta Red', '{"Pink","Red"}'),
  ('Maroon Black', '{"Maroon/Wine","Black"}'),
  ('Maroon Blue', '{"Maroon/Wine","Blue"}'),
  ('Maroon Golden', '{"Maroon/Wine","Gold/Metallic"}'),
  ('Maroon Navy Blue', '{"Maroon/Wine","Blue"}'),
  ('Mauve Pink', '{"Purple","Pink"}'),
  ('Mehendi Green - Pink', '{"Green","Pink"}'),
  ('Mehndi Blue', '{"Green","Blue"}'),
  ('Metallic Grey', '{"Grey","Gold/Metallic"}'),
  ('Moongai', '{"Green"}'),
  ('Multi Red', '{"Multi/Printed","Red"}'),
  ('Multi White', '{"Multi/Printed","White/Cream"}'),
  ('Multi Yellow', '{"Multi/Printed","Yellow"}'),
  ('Mustard Black', '{"Yellow","Black"}'),
  ('Mustard Blue', '{"Yellow","Blue"}'),
  ('Mustard Brown', '{"Yellow","Brown/Beige"}'),
  ('Mustard Magenta', '{"Yellow","Pink"}'),
  ('Mustard Orange', '{"Yellow","Orange"}'),
  ('Navy Blue Blue', '{"Blue"}'),
  ('Navy Blue Gray', '{"Blue","Grey"}'),
  ('Navy Blue Lining', '{"Blue"}'),
  ('Navy Blue Mehendi Green', '{"Blue","Green"}'),
  ('Navy Blue Pink', '{"Blue","Pink"}'),
  ('Navy Blue Red', '{"Blue","Red"}'),
  ('Navy Check', '{"Blue","Multi/Printed"}'),
  ('Navy Mustard', '{"Blue","Yellow"}'),
  ('Off White Black', '{"White/Cream","Black"}'),
  ('Off White Coffe', '{"White/Cream"}'),
  ('Off White Coffee', '{"White/Cream","Brown/Beige"}'),
  ('Off White Gazari', '{"White/Cream","Pink"}'),
  ('Off White Golden', '{"White/Cream","Gold/Metallic"}'),
  ('Off White Parrot Green', '{"White/Cream","Green"}'),
  ('Off White Pink', '{"White/Cream","Pink"}'),
  ('Off White Yellow', '{"White/Cream","Yellow"}'),
  ('Olive', '{"Green"}'),
  ('Olive Grey', '{"Grey","Green"}'),
  ('Onion Pink', '{"Pink"}'),
  ('Orange Beige', '{"Orange","Brown/Beige"}'),
  ('Orange Fawn', '{"Orange","Brown/Beige"}'),
  ('Orange Green', '{"Orange","Green"}'),
  ('Orange Grey', '{"Orange","Grey"}'),
  ('Orange Grey Brown', '{"Grey","Orange","Brown/Beige"}'),
  ('Orange Off White', '{"Orange","White/Cream"}'),
  ('Orange Parrot Green', '{"Orange","Green"}'),
  ('Orange Purple', '{"Orange","Purple"}'),
  ('Ornage Blue', '{"Blue"}'),
  ('Pale Yellow', '{"Yellow"}'),
  ('Pastel Bronze', '{"Gold/Metallic"}'),
  ('Pastel Green', '{"Green"}'),
  ('Pastel Peach', '{"Peach"}'),
  ('Peach Golden', '{"Peach","Gold/Metallic"}'),
  ('Peach Pink', '{"Peach","Pink"}'),
  ('Pink Dot', '{"Pink"}'),
  ('Pink Firozi', '{"Pink","Blue"}'),
  ('Pink Green And Red', '{"Pink","Red","Green"}'),
  ('Pink Lavender', '{"Pink","Purple"}'),
  ('Pink Peach', '{"Pink","Peach"}'),
  ('Pink Red', '{"Pink","Red"}'),
  ('Pink White', '{"Pink","White/Cream"}'),
  ('Pink Yellow', '{"Pink","Yellow"}'),
  ('Pista Black', '{"Green","Black"}'),
  ('Pista Blue', '{"Green","Blue"}'),
  ('Pista Orange', '{"Green","Orange"}'),
  ('Plum Maroon', '{"Maroon/Wine"}'),
  ('Purple Mustard', '{"Purple","Yellow"}'),
  ('Purple Pink', '{"Purple","Pink"}'),
  ('Rama Blue', '{"Green","Blue"}'),
  ('Rama Green (Morni', '{"Green"}'),
  ('Rama Green Golden', '{"Green","Gold/Metallic"}'),
  ('Rama Green Wine', '{"Green","Maroon/Wine"}'),
  ('Red Cream', '{"White/Cream","Red"}'),
  ('Red Firozi', '{"Red","Blue"}'),
  ('Red Magenta', '{"Red","Pink"}'),
  ('Red Mustard', '{"Red","Yellow"}'),
  ('Red Orange Green', '{"Red","Orange","Green"}'),
  ('Red Peach', '{"Red","Peach"}'),
  ('Red Pink', '{"Red","Pink"}'),
  ('Red-Yellow-Green', '{"Red","Yellow","Green"}'),
  ('Royal Purple', '{"Purple"}'),
  ('Rust Denim', '{"Orange"}'),
  ('Sea Green Brown', '{"Green","Brown/Beige"}'),
  ('Sea Green Magenta', '{"Green","Pink"}'),
  ('Silver', '{"Gold/Metallic"}'),
  ('Sky Blue Golden', '{"Blue","Gold/Metallic"}'),
  ('Slate', '{"Grey"}'),
  ('Slate Blue', '{"Blue"}'),
  ('Steel Grey & Red', '{"Grey","Red"}'),
  ('Teal Green', '{"Green","Blue"}'),
  ('Tie-Dye', '{"Multi/Printed"}'),
  ('Tusser Magenta', '{"Pink","Brown/Beige"}'),
  ('Tusser Red', '{"Red","Brown/Beige"}'),
  ('Violet', '{"Purple"}'),
  ('White Maroon', '{"White/Cream","Maroon/Wine"}'),
  ('White Mustard', '{"White/Cream","Yellow"}'),
  ('White Print', '{"White/Cream","Multi/Printed"}'),
  ('White Sky Blue', '{"White/Cream","Blue"}'),
  ('White With Colour', '{"Multi/Printed","White/Cream"}'),
  ('Wine Golden', '{"Maroon/Wine","Gold/Metallic"}'),
  ('Yellow Blue', '{"Yellow","Blue"}'),
  ('Yellow Firozi', '{"Yellow","Blue"}'),
  ('Yellow Gazari', '{"Yellow","Pink"}'),
  ('Yellow Green & Green Yellow', '{"Multi/Printed","Yellow","Green"}'),
  ('Yellow Maroon', '{"Yellow","Maroon/Wine"}'),
  ('Yellow Mustard', '{"Yellow"}'),
  ('Yellow Peach', '{"Yellow","Peach"}'),
  ('Yellow-Blue', '{"Yellow","Blue"}'),
  ('Yellow-Red', '{"Yellow","Red"}'),
  ('Yellow-Red-Green', '{"Yellow","Red","Green"}');

-- upsert: add new codes, refresh families on existing
insert into colors (code, families)
select code, families from colors_seed
on conflict (code) do update set families = excluded.families;

-- drop codes no longer in the reviewed set (dead junk). Safe: colors_seed is
-- the full live union, so anything absent is referenced by no column.
delete from colors c where not exists (select 1 from colors_seed s where s.code = c.code);

-- ---------------------------------------------------------------------------
-- Verify: reference matches the seed exactly; every catalog/image color maps;
-- no color has empty families. Abort on any drift.
-- ---------------------------------------------------------------------------
do $$
declare cnt int; gap int; empty_fam int;
begin
  select count(*) into cnt from colors;
  if cnt <> (select count(*) from colors_seed) then
    raise exception 'colors count % <> seed %', cnt, (select count(*) from colors_seed);
  end if;

  select count(*) into empty_fam from colors where families = '{}';
  if empty_fam > 0 then
    raise exception '% color(s) still have empty families', empty_fam;
  end if;

  select
    (select count(*) from productsizecolors p where p.color is not null and not exists (select 1 from colors c where c.code=p.color))
  + (select count(*) from mockup_variations  m where m.color is not null and not exists (select 1 from colors c where c.code=m.color))
  + (select count(*) from productimages      i where i.productcolor is not null and btrim(i.productcolor)<>'' and not exists (select 1 from colors c where c.code=i.productcolor))
  into gap;
  if gap > 0 then
    raise exception '% color value(s) across the 3 columns not in colors', gap;
  end if;
end $$;

commit;
